"""Generates the SpeakAlert launcher icon from one geometry model.

Outputs (paths relative to the repo root):
  app/src/main/res/drawable/ic_launcher_background.xml   adaptive background (vector gradient)
  app/src/main/res/drawable/ic_launcher_foreground.xml   adaptive foreground (vector)
  app/src/main/res/drawable/ic_launcher_monochrome.xml   themed-icon layer (Android 13+)
  app/src/main/res/mipmap-*/ic_launcher(_round).png       bitmaps for widgets and old launchers
  play_store_icon.png (512) and app_icon.png (1024)       store assets
  app/src/main/res/ic_launcher.png (1254)                full-size source art
  docs/icon.svg, docs/icon-512.png                       the website's icons

Everything is drawn on the adaptive-icon grid: 108x108 units, of which launchers show at least
the 66-unit circle centred at (54, 54). Run from the repo root:  python tools/icon/make_icon.py
"""
import math
import os

from PIL import Image, ImageDraw, ImageFilter

# ---- palette ---------------------------------------------------------------------------------
BG_START, BG_END = "#3B82F6", "#4338CA"      # background, top-left to bottom-right
BELL_TOP, BELL_BOTTOM = "#FFFFFF", "#E4E9FF"  # bell, a whisper of depth
BADGE_START, BADGE_END = "#60A5FA", "#2563EB"
WHITE = "#FFFFFF"
SHADOW = "#1E1B4B"

# ---- geometry (108-unit grid) ------------------------------------------------------------------
BELL = [
    ("M", 51, 31.5),
    ("C", 40.5, 31.5, 35, 39.5, 35, 50),
    ("L", 35, 60.5),
    ("C", 35, 63.5, 33.6, 65.8, 31.6, 67.8),
    ("L", 31, 69.5),
    ("L", 71, 69.5),
    ("L", 70.4, 67.8),
    ("C", 68.4, 65.8, 67, 63.5, 67, 60.5),
    ("L", 67, 50),
    ("C", 67, 39.5, 61.5, 31.5, 51, 31.5),
    ("Z",),
]
RIM = (29.5, 68.2, 72.5, 73.8, 2.8)       # rounded rect l, t, r, b, radius
KNOB = (51, 29.2, 3.3)                   # circle
CLAPPER = (51, 75.0, 5.6)                # lower half-disc, just clear of the rim
BADGE = (68.5, 39.5, 10.6)               # circle cx, cy, r
RING = 2.3                               # white ring around the badge
MIC_H = 12.2                             # mic glyph height inside the badge
SHADOW_DY, SHADOW_ALPHA = 1.2, 0.18

# The shapes above are drawn large for readability; scale the whole glyph about the icon centre
# so it sits with the same breathing room as the original icon.
SCALE = 0.84


def _pt(x, y):
    return 54 + (x - 54) * SCALE, 54 + (y - 54) * SCALE


def _scale_cmds(cmds):
    out = []
    for c in cmds:
        vals = []
        for i in range(1, len(c), 2):
            vals.extend(_pt(c[i], c[i + 1]))
        out.append((c[0], *vals))
    return out


BELL = _scale_cmds(BELL)
RIM = (*_pt(RIM[0], RIM[1]), *_pt(RIM[2], RIM[3]), RIM[4] * SCALE)
KNOB = (*_pt(KNOB[0], KNOB[1]), KNOB[2] * SCALE)
CLAPPER = (*_pt(CLAPPER[0], CLAPPER[1]), CLAPPER[2] * SCALE)
BADGE = (*_pt(BADGE[0], BADGE[1]), BADGE[2] * SCALE)
RING *= SCALE
MIC_H *= SCALE
SHADOW_DY *= SCALE


def mic_parts(cx, cy, s):
    """Rounded body, open cup arc (stroke), stem (stroke), base (rounded rect)."""
    st = s * 0.1
    top = cy - s / 2
    bw, bh = s * 0.38, s * 0.56
    body = (cx - bw / 2, top, cx + bw / 2, top + bh, bw / 2)
    r = s * 0.33
    ay = top + s * 0.36
    arc = (cx, ay, r)
    stem = (cx, ay + r, cx, cy + s / 2 - st)
    base = (cx - s * 0.2, cy + s / 2 - st, cx + s * 0.2, cy + s / 2, st / 2)
    return body, arc, stem, base, st


# ---- vector output -----------------------------------------------------------------------------
def f(v):
    return ("%.2f" % v).rstrip("0").rstrip(".")


def path_d(cmds):
    return " ".join(c[0] + ",".join(f(v) for v in c[1:]) for c in cmds)


def circle_d(cx, cy, r):
    return "M%s,%s a%s,%s 0 1,0 %s,0 a%s,%s 0 1,0 %s,0 Z" % tuple(
        f(v) for v in (cx - r, cy, r, r, 2 * r, r, r, -2 * r))


def rrect_d(l, t, r, b, rad):
    v = [l + rad, t, r - rad, t, rad, rad, r, t + rad, r, b - rad, rad, rad, r - rad, b,
         l + rad, b, rad, rad, l, b - rad, l, t + rad, rad, rad, l + rad, t]
    return ("M%s,%s L%s,%s A%s,%s 0 0,1 %s,%s L%s,%s A%s,%s 0 0,1 %s,%s "
            "L%s,%s A%s,%s 0 0,1 %s,%s L%s,%s A%s,%s 0 0,1 %s,%s Z") % tuple(f(x) for x in v)


def half_disc_d(cx, cy, r):
    return "M%s,%s L%s,%s A%s,%s 0 0,1 %s,%s Z" % tuple(f(v) for v in (cx - r, cy, cx + r, cy, r, r, cx - r, cy))


def bell_parts():
    # Separate paths on purpose: the parts overlap and wind in different directions, so one
    # combined path leaves unfilled slivers where they meet (a thin line across the rim).
    return [path_d(BELL), rrect_d(*RIM), circle_d(*KNOB), half_disc_d(*CLAPPER)]


def vector(body, aapt=False):
    ns = ' xmlns:aapt="http://schemas.android.com/aapt"' if aapt else ""
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tools/icon/make_icon.py; edit the script, not this file. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"%s\n'
            '    android:width="108dp"\n    android:height="108dp"\n'
            '    android:viewportWidth="108"\n    android:viewportHeight="108">\n%s</vector>\n') % (ns, body)


def solid(color, d, extra=""):
    return ('    <path\n        android:fillColor="%s"%s\n        android:pathData="%s" />\n'
            % (color, extra, d))


def linear(d, c1, c2, x1, y1, x2, y2):
    return ('    <path android:pathData="%s">\n'
            '        <aapt:attr name="android:fillColor">\n'
            '            <gradient android:type="linear" android:startX="%s" android:startY="%s"\n'
            '                android:endX="%s" android:endY="%s"\n'
            '                android:startColor="%s" android:endColor="%s" />\n'
            '        </aapt:attr>\n    </path>\n') % (d, f(x1), f(y1), f(x2), f(y2), c1, c2)


def stroke(color, d, width):
    return ('    <path\n        android:strokeColor="%s"\n        android:strokeWidth="%s"\n'
            '        android:strokeLineCap="round"\n        android:pathData="%s" />\n') % (color, f(width), d)


def mic_vector(color):
    body, (ax, ay, r), (sx1, sy1, sx2, sy2), base, st = mic_parts(BADGE[0], BADGE[1], MIC_H)
    a0, a1 = math.radians(8), math.radians(172)
    rr = r - st / 2
    arc = "M%s,%s A%s,%s 0 0,0 %s,%s" % tuple(f(v) for v in (
        ax + rr * math.cos(a0), ay + rr * math.sin(a0), rr, rr, ax + rr * math.cos(a1), ay + rr * math.sin(a1)))
    # sweep flag 1 goes clockwise (down through the bottom) in screen coordinates
    arc = arc.replace(" 0 0,0 ", " 0 0,1 ")
    return (solid(color, rrect_d(*body)) + stroke(color, arc, st)
            + stroke(color, "M%s,%s L%s,%s" % tuple(f(v) for v in (sx1, sy1 - st / 2, sx2, sy2)), st)
            + solid(color, rrect_d(*base)))


def background_xml():
    return vector(linear("M0,0 L108,0 L108,108 L0,108 Z", BG_START, BG_END, 0, 0, 108, 108), aapt=True)


def foreground_xml():
    shadow_alpha = "\n        android:fillAlpha=\"%s\"" % f(SHADOW_ALPHA)
    cx, cy, r = BADGE
    body = ""
    body += '    <group android:translateY="%s">\n' % f(SHADOW_DY)
    body += "".join(solid(SHADOW, d, shadow_alpha) for d in bell_parts())
    body += solid(SHADOW, circle_d(cx, cy, r + RING), shadow_alpha)
    body += '    </group>\n'
    body += "".join(linear(d, BELL_TOP, BELL_BOTTOM, 0, 29, 0, 80) for d in bell_parts())
    body += solid(WHITE, circle_d(cx, cy, r + RING))
    body += linear(circle_d(cx, cy, r), BADGE_START, BADGE_END, cx - r, cy - r, cx + r, cy + r)
    body += mic_vector(WHITE)
    return vector(body, aapt=True)


def monochrome_xml():
    # Themed icons use alpha only, so nothing can be painted "in white on blue": the ring becomes
    # a gap clipped out of the bell, and the mic body and base are even-odd holes in the badge.
    cx, cy, r = BADGE
    body_r, _, _, base_r, _ = mic_parts(cx, cy, MIC_H)
    out = '    <group>\n        <clip-path android:pathData="%s" />\n' % _outside(cx, cy, r + RING)
    out += "".join(solid(WHITE, d) for d in bell_parts())
    out += "    </group>\n"
    out += solid(WHITE, " ".join([circle_d(cx, cy, r), rrect_d(*body_r), rrect_d(*base_r)]),
                 '\n        android:fillType="evenOdd"')
    return vector(out)


def _outside(cx, cy, r):
    """Clip region: the canvas minus a circle, as a polygon notch (clip-path cannot subtract)."""
    pts = []
    n = 64
    for i in range(n + 1):
        a = math.radians(90 + 360 * i / n)
        pts.append((cx + r * math.cos(a), cy - r * math.sin(a)))
    d = "M0,0 L%s,0 L%s,%s " % (f(cx), f(cx), f(cy - r))
    d += " ".join("L%s,%s" % (f(x), f(y)) for x, y in pts)
    d += " L%s,0 L108,0 L108,108 L0,108 Z" % f(cx)
    return d


# ---- raster output (same geometry) -------------------------------------------------------------
def hexrgb(c):
    c = c.lstrip("#")
    return tuple(int(c[i:i + 2], 16) for i in (0, 2, 4))


def sample(cmds, steps=48):
    pts, cur = [], (0, 0)
    for c in cmds:
        if c[0] in "ML":
            cur = (c[1], c[2]); pts.append(cur)
        elif c[0] == "C":
            x0, y0 = cur
            x1, y1, x2, y2, x3, y3 = c[1:]
            for i in range(1, steps + 1):
                t = i / steps; m = 1 - t
                pts.append((m**3*x0 + 3*m*m*t*x1 + 3*m*t*t*x2 + t**3*x3, m**3*y0 + 3*m*m*t*y1 + 3*m*t*t*y2 + t**3*y3))
            cur = (x3, y3)
    return pts


def grad_img(size, c1, c2, horizontal_diag=True):
    a, b = hexrgb(c1), hexrgb(c2)
    small = Image.new("RGB", (64, 64))
    px = small.load()
    for y in range(64):
        for x in range(64):
            t = (x + y) / 126 if horizontal_diag else y / 63
            px[x, y] = tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))
    return small.resize((size, size), Image.BICUBIC)


def render_full(size):
    """The full 108-unit square: background plus foreground."""
    ss = 3
    S = size * ss
    k = S / 108
    P = lambda x, y: (x * k, y * k)
    img = grad_img(S, BG_START, BG_END).convert("RGBA")

    def glyph_mask(extra_ring=False):
        m = Image.new("L", (S, S), 0)
        d = ImageDraw.Draw(m)
        d.polygon([P(*p) for p in sample(BELL)], fill=255)
        l, t, r, b, rad = RIM
        d.rounded_rectangle([*P(l, t), *P(r, b)], radius=rad * k, fill=255)
        x, y, rr = KNOB
        d.ellipse([*P(x - rr, y - rr), *P(x + rr, y + rr)], fill=255)
        x, y, rr = CLAPPER
        d.pieslice([*P(x - rr, y - rr), *P(x + rr, y + rr)], 0, 180, fill=255)
        return m

    bell_m = glyph_mask()
    cx, cy, r = BADGE
    ring_m = Image.new("L", (S, S), 0)
    ImageDraw.Draw(ring_m).ellipse([*P(cx - r - RING, cy - r - RING), *P(cx + r + RING, cy + r + RING)], fill=255)
    # shadow: bell + ring, offset down, soft
    sh = Image.new("L", (S, S), 0)
    sh.paste(255, (0, 0), bell_m)
    sh.paste(255, (0, 0), ring_m)
    sh = sh.filter(ImageFilter.GaussianBlur(1.1 * k))
    sh_layer = Image.new("RGBA", (S, S), hexrgb(SHADOW) + (0,))
    sh_layer.putalpha(sh.point(lambda v: int(v * SHADOW_ALPHA * 1.4)))
    img.alpha_composite(sh_layer, (0, int(SHADOW_DY * k)))
    # bell with vertical gradient
    bell_g = Image.new("RGBA", (S, S))
    top, bot = hexrgb(BELL_TOP), hexrgb(BELL_BOTTOM)
    col = Image.new("RGB", (1, 256))
    for i in range(256):
        yy = i / 255 * 108
        t = min(1, max(0, (yy - 29) / 51))
        col.putpixel((0, i), tuple(int(top[j] + (bot[j] - top[j]) * t) for j in range(3)))
    bell_g.paste(col.resize((S, S)), (0, 0))
    img.paste(bell_g, (0, 0), bell_m)
    # ring and badge
    img.paste(Image.new("RGB", (S, S), WHITE), (0, 0), ring_m)
    badge_m = Image.new("L", (S, S), 0)
    ImageDraw.Draw(badge_m).ellipse([*P(cx - r, cy - r), *P(cx + r, cy + r)], fill=255)
    img.paste(grad_img(S, BADGE_START, BADGE_END), (0, 0), badge_m)
    # mic
    d = ImageDraw.Draw(img)
    body, (ax, ay, rr), (sx1, sy1, sx2, sy2), base, st = mic_parts(cx, cy, MIC_H)
    l, t, rgt, b, rad = body
    d.rounded_rectangle([*P(l, t), *P(rgt, b)], radius=rad * k, fill=WHITE)
    d.arc([*P(ax - rr, ay - rr), *P(ax + rr, ay + rr)], 8, 172, fill=WHITE, width=max(1, int(st * k)))
    for ang in (8, 172):
        a = math.radians(ang)
        x, y = ax + (rr - st / 2) * math.cos(a), ay + (rr - st / 2) * math.sin(a)
        d.ellipse([*P(x - st / 2, y - st / 2), *P(x + st / 2, y + st / 2)], fill=WHITE)
    d.line([*P(sx1, sy1 - st / 2), *P(sx2, sy2)], fill=WHITE, width=max(1, int(st * k)))
    l, t, rgt, b, rad = base
    d.rounded_rectangle([*P(l, t), *P(rgt, b)], radius=rad * k, fill=WHITE)
    return img.resize((size, size), Image.LANCZOS)


def crop_visible(img):
    """What a launcher shows: the middle 72 of 108 units."""
    s = img.size[0]
    a = int(s * 18 / 108)
    return img.crop((a, a, s - a, s - a))


def masked(img, shape):
    s = img.size[0]
    m = Image.new("L", (s, s), 0)
    d = ImageDraw.Draw(m)
    if shape == "round":
        d.ellipse([0, 0, s - 1, s - 1], fill=255)
    else:
        d.rounded_rectangle([0, 0, s - 1, s - 1], radius=int(s * 0.23), fill=255)
    out = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    out.paste(img, (0, 0), m)
    return out


def svg_icon():
    """The same icon as a standalone SVG (for the website), cropped to the visible area."""
    cx, cy, r = BADGE
    body, (ax, ay, rr), (sx1, sy1, sx2, sy2), base, st = mic_parts(cx, cy, MIC_H)
    a0, a1 = math.radians(8), math.radians(172)
    ra = rr - st / 2
    arc = "M%s,%s A%s,%s 0 0,1 %s,%s" % tuple(f(v) for v in (
        ax + ra * math.cos(a0), ay + ra * math.sin(a0), ra, ra, ax + ra * math.cos(a1), ay + ra * math.sin(a1)))
    shadow = "".join('    <path d="%s" fill="%s" fill-opacity="%s" transform="translate(0 %s)"/>\n'
                     % (d, SHADOW, f(SHADOW_ALPHA), f(SHADOW_DY)) for d in bell_parts())
    shadow += '    <path d="%s" fill="%s" fill-opacity="%s" transform="translate(0 %s)"/>\n' % (
        circle_d(cx, cy, r + RING), SHADOW, f(SHADOW_ALPHA), f(SHADOW_DY))
    bell = "".join('    <path d="%s" fill="url(#bell)"/>\n' % d for d in bell_parts())
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" role="img" aria-label="SpeakAlert icon">\n'
            '  <!-- Generated by tools/icon/make_icon.py; edit the script, not this file. -->\n'
            '  <defs>\n'
            '    <linearGradient id="bg" x1="0" y1="0" x2="108" y2="108" gradientUnits="userSpaceOnUse">'
            '<stop offset="0" stop-color="%s"/><stop offset="1" stop-color="%s"/></linearGradient>\n'
            '    <linearGradient id="bell" x1="0" y1="29" x2="0" y2="80" gradientUnits="userSpaceOnUse">'
            '<stop offset="0" stop-color="%s"/><stop offset="1" stop-color="%s"/></linearGradient>\n'
            '    <linearGradient id="badge" x1="%s" y1="%s" x2="%s" y2="%s" gradientUnits="userSpaceOnUse">'
            '<stop offset="0" stop-color="%s"/><stop offset="1" stop-color="%s"/></linearGradient>\n'
            '  </defs>\n'
            '  <rect x="18" y="18" width="72" height="72" rx="16.5" fill="url(#bg)"/>\n'
            '  <g>\n%s%s'
            '    <path d="%s" fill="%s"/>\n'
            '    <path d="%s" fill="url(#badge)"/>\n'
            '    <path d="%s" fill="%s"/>\n'
            '    <path d="%s" fill="none" stroke="%s" stroke-width="%s" stroke-linecap="round"/>\n'
            '    <path d="M%s,%s L%s,%s" fill="none" stroke="%s" stroke-width="%s" stroke-linecap="round"/>\n'
            '    <path d="%s" fill="%s"/>\n'
            '  </g>\n</svg>\n') % (
        BG_START, BG_END, BELL_TOP, BELL_BOTTOM,
        f(cx - r), f(cy - r), f(cx + r), f(cy + r), BADGE_START, BADGE_END,
        shadow, bell,
        circle_d(cx, cy, r + RING), WHITE,
        circle_d(cx, cy, r),
        rrect_d(*body), WHITE,
        arc, WHITE, f(st),
        f(sx1), f(sy1 - st / 2), f(sx2), f(sy2), WHITE, f(st),
        rrect_d(*base), WHITE)


def main():
    res = "app/src/main/res"
    open("docs/icon.svg", "w", encoding="utf-8", newline="\n").write(svg_icon())
    w = lambda p, t: open(os.path.join(res, p), "w", encoding="utf-8", newline="\n").write(t)
    w("drawable/ic_launcher_background.xml", background_xml())
    w("drawable/ic_launcher_foreground.xml", foreground_xml())
    w("drawable/ic_launcher_monochrome.xml", monochrome_xml())
    big = render_full(1296)                       # 12x the 108 grid
    visible = crop_visible(big)                   # 864 px of the visible area
    for folder, size in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
        out = os.path.join(res, "mipmap-" + folder)
        v = visible.resize((size, size), Image.LANCZOS)
        masked(v, "square").save(os.path.join(out, "ic_launcher.png"))
        masked(v, "round").save(os.path.join(out, "ic_launcher_round.png"))
        stale = os.path.join(out, "ic_launcher_foreground.png")
        if os.path.exists(stale):
            os.remove(stale)
    # Play Store: full-bleed square, Play applies its own mask.
    crop_visible(render_full(768)).resize((512, 512), Image.LANCZOS).convert("RGBA").save("play_store_icon.png")
    # The website's raster icon for link previews (social sites do not render SVG).
    Image.open("play_store_icon.png").save("docs/icon-512.png")
    # Full-size source art kept alongside the resources (not itself a resource).
    masked(visible.resize((1254, 1254), Image.LANCZOS), "square").save(os.path.join(res, "ic_launcher.png"))
    masked(visible.resize((1024, 1024), Image.LANCZOS), "square").save("app_icon.png")
    print("icon generated")


if __name__ == "__main__":
    main()
